config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:index, :create, :show, :edit, :update]

  get 'homes/top'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :books

   def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(resource)
  end
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if  @book.save
      redirect_to book_path(@book)
    else
      @books = Book.all
      render 'index'
    end
  end

  def index
    @book = Book.new
    @books = Book.all.includes(:user)
  end

  def show
    @book = Book.new
  end
  
  def edit
  end
  
private

def book_params
  params.require(:book).permit(:title, :body)
end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
  end
end


private

def user_params
  params.require(:user).permmit(:name, :introduction, :profile_image)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model:@book do |f| %>
<div class="form-group"></div>
<%= f.text_field :title %><br>
<%= f.text_area :body %><br>
<%= f.submit 'Create Book' %>
<% end %>

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<h2>User info</h2>
<%= render 'users/info', user: current_user %>>

<h2>New book</h2>
<%= form_with model:@book do |f| %>
<%= f.text_field :title %><br>
<%= f.text_area :body %><br>
<%= f.submit 'Create Book' %>
<% end %>


<h2>Books</h2>
<table>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td></td>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

app/views/homes/about.html.erb
about

app/views/homes/top.html.erb
<h1>Homes#top</h1>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/"><span>bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

        <% if user_signed_in? %>
          <li>
            <%= link_to "HOME", user_path(current_user) %>
          </li>
          <li>
            <%= link_to "Users", users_path %>
          </li>
          <li>
            <%= link_to "Books", books_path %>
          </li>
          <li>
              <%= link_to "Log out", destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li>
            <%= link_to 'Home', root_path %>
          </li>
          <li>
            <%= link_to 'About', home_about_path %>
          </li>
          <li>
              <%= link_to "Sign up", new_user_registration_path %>
          </li>
          <li>
              <%= link_to "Log in", new_user_session_path %>
          </li>
        <% end %>



        </ul>
      </div>
    </div>
   </nav>
</header>










</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Practice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/1a4c15eed2.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    
    
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/_info.html.erb
<table>
  <tbody>
      <tr>
          <td><%= image_tag current_user.get_profile_image(100,100) %></td>
      </tr>
      <tr>
          <td>name</td>
          <td><%= user.name %></td>
      </tr>
      <tr>
          <td>introduction</td>
          <td><%= user.introduction %></td>
      </tr>
  </tbody>
</table>
<div class='row'>
    <%= link_to edit_user_path(current_user) do %>
        <i class="fas fa-user-cog"></i>
    <% end %>
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h2>user </h2>




<h2>New book</h2>
<%= form_with model:@book do |f| %>
<%= f.text_field :title %><br>
<%= f.text_area :body %><br>
<%= f.submit 'Create Book' %>
<% end %>


<h2>Books</h2>
<table>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>
  
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td><%= image_tag @user.get_profile_image(100,100) %></td>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
    </tr>
    <% end %>
  </tbody>
</table>